FROM amazoncorretto:21

WORKDIR /app

COPY ./maven-samples/single-module/target/*.jar /app/single-module-project.jar

ENV SERVER_PORT=8080

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "single-module-project.jar"]